name: quotes_status_creator
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.2
  card_swiper: ^2.0.4
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  dotted_border: ^2.0.0+2
  expandable_menu: ^0.0.5
  firebase_database: ^10.0.1
  flex_color_scheme: ^6.1.1
  flutter:
    sdk: flutter
  flutter_color_picker:
    path: ../flutter_color_picker
  flutter_email_sender: ^5.2.0
  flutter_flip_card: ^0.0.3
  flutter_riverpod: ^2.0.2
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.3.0
  gradient_colors:
    path: ../gradient_colors
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  http: ^0.13.0
  image: ^3.2.2
  image_cropper: ^3.0.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.6
  internet_connection_checker: ^1.0.0+1
  new_gradient_app_bar: ^0.2.0
  path_provider: ^2.0.11
  permission_handler: ^9.2.0
  provider: ^6.0.4
  receive_sharing_intent: ^1.4.5
  riverpod_generator: ^1.0.4
  screenshot: ^1.2.3
  shared_preferences: ^2.0.15
  showcaseview: ^1.1.8
  social_share: ^2.2.1
  store_redirect: ^2.0.1
  text_style_editor:
    path: ../text_style_editor
  toast: ^0.3.0
  url_launcher: ^6.1.7
dependency_overrides:
  # for dio_http_cache
  json_serializable: ^4.1.4
  analyzer: ^4.0.0

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icon/
    - assets/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: Arizonia
      fonts:
        - asset: assets/fonts/Arizonia-Regular.ttf
    - family: ChunkFive
      fonts:
        - asset: assets/fonts/ChunkFive-Regular.otf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster_1.3.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OstrichSans
      fonts:
        - asset: assets/fonts/OstrichSans-Medium.otf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.otf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: SEASRN
      fonts:
        - asset: assets/fonts/SEASRN.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
